services:
  app:
    build: ./app
    ports:
      - 8080:8080
    volumes:
      - ./app/:/app
      - /app/node_modules
      - /app/.pnpm-store
  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
  loki:
    build: ./loki
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
  alloy:
    build: ./alloy
    ports:
      - 12345:12345
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # docker上で動いているdaemonを見つけられるように
    depends_on:
      - loki
      - app

volumes:
  grafana-data:
  loki-data:
